name: Lint

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  setup:
    uses: ./.github/workflows/setup.yaml

  lint:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run lint
        run: pnpm lint
